<?php
/**
 * @var $this   N2View
 * @var $_class N2SmartsliderBackendSlidersView
 */

$this->widget->init('topbar');

$this->widget->init('heading', array(
    'title'   => n2_('Dashboard') . N2Html::tag('span', array(), n2_('Version') . ': ' . N2SS3::$version . '-' . N2SS3::$plan . ' - <a target="_blank" href="http://doc.smartslider3.com/article/432-changelog">' . n2_('Changelog') . '</a>'),
    'actions' => $_class->getDashboardButtons()
));
?>

<?php
$this->renderInline("tutorial-free");

?>

    <div class="n2-ss-sliders-outer-container">
        <?php
        $this->renderInline("slidermanager", array(
            'groupID' => 0
        ));
        ?>
    </div>

<?php N2SS3::showBeacon('Main page, Import, Update'); ?>